services:
  postgres:
    container_name: strohm_db
    image: postgres:16.6
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d postgres'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports: # For development only, in production we don't need to expose the port
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEVELOPMENT_PASSWORD}
    volumes:
      - main_db_data:/var/lib/postgresql/data

  node:
    image: node:lts-bookworm-slim
    container_name: strohm_backend
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    restart:
      unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=dev
      - SERVER_OIDC_SECRET=${SERVER_DEVELOPMENT_OIDC_SECRET}
      - SERVER_OIDC_CLIENT_ID=${SERVER_DEVELOPMENT_OIDC_CLIENT_ID}
      - SERVER_OIDC_ISSUER_BASE_URL=${SERVER_DEVELOPMENT_OIDC_ISSUER_BASE_URL}
      - SERVER_OIDC_BASE_URL=${SERVER_DEVELOPMENT_BASE_URL}
      - SERVER_OIDC_CLIENT_SECRET=${SERVER_DEVELOPMENT_OIDC_CLIENT_SECRET}
      - ODOO_ADMIN_API_KEY=${ODOO_DEVELOPMENT_ADMIN_API_KEY}
      - ODOO_API_SECRET='anothersecret'
      - ODOO_HOST=odoo
      - DB_HOST=postgres
      - DB_NAME=${STROHM_DB}
      - DB_USER=${STROHM_DB_USER}
      - DB_PASSWORD=${STROHM_DB_PASSWORD}
      - DB_PORT=5432
    command: npx nodemon server.js


  odoo:
    container_name: strohm_odoo
    image: "ghcr.io/mincomsmartsolutions/odoo:18.0"
    ports:
      - "8069:8069"
    environment:
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-devel}"
      ODOO_API_SECRET: "anothersecret" #secret shared with node instance to allow decrypt of userapi keys
      INITIAL_LANG: "de_DE"
      LIST_DB: "true"
      PGHOST: postgres
      PGUSER: ${ODOO_DB_USER}
      PGPASSWORD: ${ODOO_DB_DEVELOPMENT_PASSWORD}
      PGDATABASE: ${ODOO_DB}
      ADMIN_PASSWORD: ${ODOO_PASSWORD}
      SMTP_PORT: "1025"
      EMAIL_FROM: ${SMTP_USER}
      WITHOUT_DEMO: "${DOODBA_WITHOUT_DEMO-all}"
    tty: true
    volumes:
      - odoo-strohm-web-data:/var/lib/odoo
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - odoo
      - --load-language=de_DE

volumes:
  main_db_data:
  odoo-strohm-web-data:
