services:
  db:
    container_name: strohm_db
    image: postgres:16.6
    restart:
      unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d postgres'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports: # For development only, in production we don't need to expose the port
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEVELOPMENT_PASSWORD}
    volumes:
      - main-db-data:/var/lib/postgresql/data

  server:
    container_name: strohm_backend
    image: node:lts-bookworm-slim
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    restart:
      unless-stopped
    depends_on:
      db:
        condition: service_healthy
    #      odoo:
    #        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
    environment:
      NODE_ENV: dev
      SERVER_OIDC_SECRET: ${SERVER_DEVELOPMENT_OIDC_SECRET}
      SERVER_OIDC_CLIENT_ID: ${SERVER_DEVELOPMENT_OIDC_CLIENT_ID}
      SERVER_OIDC_ISSUER_BASE_URL: ${SERVER_DEVELOPMENT_OIDC_ISSUER_BASE_URL}
      SERVER_OIDC_BASE_URL: ${SERVER_DEVELOPMENT_BASE_URL}
      SERVER_OIDC_CLIENT_SECRET: ${SERVER_DEVELOPMENT_OIDC_CLIENT_SECRET}
      STEVE_HOST: steve
      STEVE_PORT: 8180
      STEVE_AUTH_USERNAME: ${STEVE_DEVELOPMENT_AUTH_USERNAME}
      STEVE_API_PASSWORD: ${STEVE_DEVELOPMENT_API_PASSWORD}
      ODOO_ADMIN_API_KEY: ${ODOO_DEVELOPMENT_ADMIN_API_KEY}
      ODOO_API_SECRET: anothersecret
      ODOO_HOST: odoo
      ODOO_PORT: 8069
      ODOO_EXTERNAL_HOST: localhost
      ODOO_EXTERNAL_PORT: 18069
      DB_HOST: db
      DB_NAME: ${STROHM_DB}
      DB_USER: ${STROHM_DB_USER}
      DB_PASSWORD: ${STROHM_DB_PASSWORD}
      DB_PORT: 5432
    command: npx nodemon server.js

  odoo:
    container_name: strohm_odoo
    build:
      context: ./odoo-strohm/odoo
      args:
        DB_VERSION: "16"
        ODOO_VERSION: "18.0"
        AGGREGATE: "false"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
        PIP_INSTALL_ODOO: 1
        CLEAN: "false"
        COMPILE: "false"
    #    healthcheck:
    #      test: [ "CMD", "curl", "-f", "http://odoo:8069/" ]
    #      interval: 30s        # run every 30 seconds
    #      timeout: 10s         # wait up to 10 seconds for a response
    #      retries: 5           # retry 5 times before marking unhealthy
    #      start_period: 60s    # allow 60 seconds for Odoo to start
    environment:
      ODOO_ENV: "dev"
      LIST_DB: "true"
      PGHOST: db
      PGDATABASE: ${ODOO_DB}
      PGUSER: ${ODOO_DB_USER}
      PGPASSWORD: ${ODOO_DB_DEVELOPMENT_PASSWORD}
      ADMIN_PASSWORD: ${ODOO_PASSWORD}
      PYTHONDONTWRITEBYTECODE: 1
      SMTP_PORT: "1025"
      ODOO_API_SECRET: anothersecret
      INITIAL_LANG: "de_DE"
      BACKEND_HOST: server
      BACKEND_PORT: 3000
      WITHOUT_DEMO: "all"
      PROXY_MODE: "false"
      DEBUGPY_ENABLE: 0
    tty: true
    ports:
      #      - "127.0.0.1:6899:6899" # Debugpy
      - "127.0.0.1:18069:8069"
      - "127.0.0.1:18072:8072"
    volumes:
      - ./odoo-strohm/odoo/custom:/opt/odoo/custom:ro,z
      - ./odoo-strohm/odoo/auto:/opt/odoo/auto:rw,z
      - odoo-web-data:/var/lib/odoo:z
    depends_on:
      db:
        condition: service_healthy
    command:
      - odoo
      - --limit-memory-soft=0
      - --limit-time-real-cron=9999999
      - --limit-time-real=9999999
      - --workers=0
      - --dev=reload,qweb,werkzeug,xml
      - -i strohm_addon

  steve-db:
    container_name: steve_sim_db
    image: mariadb:10.4.30
    ports:
      - "3306:3306"
    volumes:
      - steve-db-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: stevedb
      MYSQL_USER: steve
      MYSQL_PASSWORD: changeme

  steve:
    container_name: steve_sim
    build: ./steve
    links:
      - "steve-db:mariadb"
    volumes:
      - ./steve:/code
      - steve-jars:/root/.m2
    ports:
      - "8180:8180"
      - "8443:8443"
    depends_on:
      - steve-db

  stripe:
    container_name: stripe_dev
    image: stripe/stripe-cli:latest
    depends_on:
      - odoo
    environment:
      STRIPE_API_KEY: ${STRIPE_DEVELOPMENT_API_KEY}
      STRIPE_DEVICE_NAME: ${STRIPE_DEVELOPMENT_DEVICE_NAME}
    command: >
      listen --forward-to odoo:8069/payment/stripe/webhook/



volumes:
  main-db-data:
  odoo-web-data: # filestore
  steve-db-data:
  steve-jars:

networks:
  default:
  public: