services:
  db:
    image: postgres:16.6
    container_name: strohm_user_test_db
    restart: unless-stopped
    volumes:
      - strohm-user-test-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "testpassword"
    ports:
      - "${STROHM_DB_PORT:-5432}:${STROHM_DB_PORT:-5432}"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'" ]
      interval: 10s
      timeout: 3s
      retries: 5

  server:
    image: ghcr.io/mincomsmartsolutions/strohm_backend:latest
    container_name: strohm_user_test_backend
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-3000}:${SERVER_PORT:-3000}"
    depends_on:
      db:
        condition: service_healthy
      steve:
        condition: service_healthy
    environment:
      NODE_ENV: dev
      NODE_PORT: ${SERVER_PORT:-3000}
      SERVER_OIDC_SECRET: ${SERVER_OIDC_SECRET}
      SERVER_OIDC_CLIENT_ID: ${SERVER_OIDC_CLIENT_ID}
      SERVER_OIDC_ISSUER_BASE_URL: ${SERVER_OIDC_ISSUER_BASE_URL}
      SERVER_OIDC_BASE_URL: ${SERVER_BASE_URL}
      SERVER_OIDC_CLIENT_SECRET: ${SERVER_OIDC_CLIENT_SECRET}
      STROHM_DB_HOST: db
      STROHM_DB_NAME: ${STROHM_DB:-strohm}
      STROHM_DB_USER: "admin"
      STROHM_DB_PASSWORD: "testpassword"
      STROHM_DB_PORT: ${STROHM_DB_PORT:-5432}
      STEVE_HOST: steve
      STEVE_PORT: 8180
      STEVE_BASE_URL: http://steve:8180/steve
      STEVE_AUTH_USERNAME: ${STEVE_AUTH_USERNAME:-admin}
      STEVE_API_PASSWORD: ${STEVE_API_PASSWORD:-1234api}
      ODOO_API_SECRET: "user_test_secret"
      ODOO_HOST: odoo
      ODOO_PORT: ${ODOO_PORT:-8069}
      ODOO_EXTERNAL_BASE_URL: http://localhost:1${ODOO_PORT:-8069}
      SESSION_SECRET: "very_secret_session_key_here18237189239819283"
      WEBHOOK_API_KEY: "webhook_key_here"
      TAILSCALE_ENABLE_ADMIN: true
      TAILSCALE_ALLOWED_RANGES: "0.0.0.0/0,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16"

  odoo:
    container_name: strohm_user_test_odoo
    image: ghcr.io/mincomsmartsolutions/odoo:latest
    restart: unless-stopped
    environment:
      ODOO_ENV: "dev"
      DB_VERSION: "16"
      DB_FILTER: "^odoo$"
      LIST_DB: "true"
      ODOO_VERSION: "18.0"
      AGGREGATE: "true"
      UID: "${UID:-1000}"
      GID: "${GID:-1000}"
      PIP_INSTALL_ODOO: 1
      INITIAL_LANG: "de_DE"
      PGHOST: db
      PGDATABASE: "odoo"
      PGUSER: "admin"
      PGPASSWORD: "testpassword"
      ADMIN_PASSWORD: admin
      PYTHONDONTWRITEBYTECODE: 1
      ODOO_API_SECRET: "user_test_secret"
      WITHOUT_DEMO: all
      PROXY_MODE: false
      BACKEND_HOST: server
      BACKEND_PORT: ${NODE_PORT:-3000}
      BACKEND_EXTERNAL_URL: http://localhost:${NODE_PORT:-3000}
      WEBHOOK_API_KEY: "webhook_key_here"
    volumes:
      - odoo-user-test-web-data:/var/lib/odoo:z
    tty: true
    ports:
      - "127.0.0.1:${ODOO_EXTERNAL_PORT:-18069}:8069"
    depends_on:
      db:
        condition: service_healthy
    command:
      - odoo
      - --database=odoo
      - --db-filter=^odoo$
      - --init=base,strohm_addon
      - --load-language=de_DE


  steve-db:
    image: mariadb:10.4.30
    container_name: strohm_user_test_steve_db
    restart: unless-stopped
    volumes:
      - steve-user-test-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: stevedb
      MYSQL_USER: steve
      MYSQL_PASSWORD: changeme

  steve:
    build: ./steve
    container_name: strohm_user_test_steve
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8180 || exit 1" ]
      interval: 8s
      timeout: 3s
      retries: 40
    links:
      - "steve-db:mariadb"
    depends_on:
      - steve-db
    environment:
      DB_HOST: steve-db
      DB_NAME: stevedb
      DB_USER: steve
      DB_PASSWORD: changeme
    ports:
      - "${STEVE_HTTP_PORT:-8180}:${STEVE_HTTP_PORT:-8180}"
    volumes:
      - steve-user-test-jars:/root/.m2

  ocpp-wallbox-sim:
    image: ghcr.io/mincomsmartsolutions/ocppwallboxsim:latest
    container_name: strohm_user_test_ocpp_wallbox_sim
    restart: unless-stopped
    ports:
      - "8090:80"


volumes:
  steve-user-test-jars:
  steve-user-test-db-data:
  strohm-user-test-db-data:
  odoo-user-test-web-data:

networks:
  default:
