services:
  db:
    image: postgres:16.6
    container_name: strohm_user_test_db
    volumes:
      - ./database/init.d/postgresql/clean:/docker-entrypoint-initdb.d:ro
      - strohm-user-test-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "testpassword"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U admin -d postgres'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  odoo:
    container_name: odoo_user_test
    image: ghcr.io/mincomsmartsolutions/odoo:latest
    environment:
      ODOO_ENV: "test"
      DB_VERSION: "16"
      ODOO_VERSION: "18.0"
      AGGREGATE: "true"
      UID: "${UID:-1000}"
      GID: "${GID:-1000}"
      PIP_INSTALL_ODOO: 1
      CLEAN: "true"
      COMPILE: "false"
      PGHOST: db
      INITIAL_LANG: "de_DE"
      PGDATABASE: odoo
      PGUSER: odoo_admin
      PGPASSWORD: ${ODOO_DB_DEVELOPMENT_PASSWORD}
      ADMIN_PASSWORD: admin
      PYTHONDONTWRITEBYTECODE: 1
      ODOO_API_SECRET: "user_test_secret"
      WITHOUT_DEMO: true
      PROXY_MODE: false
      BACKEND_PORT: 3000
      BACKEND_HOST: server
    volumes:
      - odoo-user-test-web-data:/var/lib/odoo:z
    tty: true
    ports:
      - "127.0.0.1:18069:8069"
    depends_on:
      db:
        condition: service_healthy
    command:
      - odoo
      - -i base,base_automation,portal,account,payment,sale,l10n_de,strohm_addon \
      - --load-language=de_DE


  steve-db:
    image: mariadb:10.4.30
    container_name: steve_user_test_db
    volumes:
      - steve-user-test-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: stevedb
      MYSQL_USER: steve
      MYSQL_PASSWORD: changeme

  steve:
    build: ./steve
    container_name: steve_user_test
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8180 || exit 1" ]
    links:
      - "steve-db:mariadb"
    depends_on:
      - steve-db
    environment:
      DB_HOST: steve-db
      DB_NAME: stevedb
      DB_USER: steve
      DB_PASSWORD: changeme
    ports:
      - "8180:8180"
    volumes:
      - steve-user-test-jars:/root/.m2

  ocpp-wallbox-sim:
    image: ghcr.io/mincomsmartsolutions/ocppwallboxsim:latest
    ports:
      - "8090:80"

  server:
    build: ./backend
    container_name: user_test_backend
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules  # Preserve node_modules from Docker build
    environment:
      NODE_ENV: development
      SERVER_OIDC_SECRET: ${SERVER_DEVELOPMENT_OIDC_SECRET}
      SERVER_OIDC_CLIENT_ID: ${SERVER_DEVELOPMENT_OIDC_CLIENT_ID}
      SERVER_OIDC_ISSUER_BASE_URL: ${SERVER_DEVELOPMENT_OIDC_ISSUER_BASE_URL}
      SERVER_OIDC_BASE_URL: ${SERVER_DEVELOPMENT_BASE_URL}
      SERVER_OIDC_CLIENT_SECRET: ${SERVER_DEVELOPMENT_OIDC_CLIENT_SECRET}
      STEVE_HOST: steve
      STEVE_PORT: 8180
      STEVE_AUTH_USERNAME: admin
      STEVE_API_PASSWORD: 1234api
      ODOO_ADMIN_API_KEY: ${ODOO_DEVELOPMENT_ADMIN_API_KEY}
      ODOO_API_SECRET: "user_test_secret"
      ODOO_HOST: odoo
      ODOO_PORT: 8069
      ODOO_EXTERNAL_HOST: localhost
      ODOO_EXTERNAL_PORT: 18069
      WEBHOOK_API_KEY: test_webhook_api_key
      DB_HOST: db
      DB_NAME: strohm
      DB_USER: strohm_admin
      DB_PASSWORD: ${STROHM_DB_PASSWORD}
      DB_PORT: 5432
    command: npx nodemon server.js

volumes:
  steve-user-test-jars:
  steve-user-test-db-data:
  strohm-user-test-db-data:
  odoo-user-test-web-data:

networks:
  default:
